apiVersion: apps/v1
kind: Deployment
metadata:
  name: circle
  labels:
    app: circle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circle
  template:
    metadata:
      labels:
        app: circle
    spec:
      containers:
        - name: circle
          image: circle
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
