apiVersion: apps/v1
kind: Deployment
metadata:
  name: square
  labels:
    app: square
spec:
  replicas: 1
  selector:
    matchLabels:
      app: square
  template:
    metadata:
      labels:
        app: square
    spec:
      containers:
        - name: square
          image: square
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
