apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\L03566021\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: triangle
  name: triangle
spec:
  ports:
    - name: "5100"
      port: 5100
      targetPort: 5001
  selector:
    io.kompose.service: triangle
