apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\L03566021\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: triangle
  name: triangle
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: triangle
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\L03566021\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: triangle
    spec:
      containers:
        - image: triangle
          name: triangle
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
