apiVersion: apps/v1
kind: Deployment
metadata:
  name: triangle
  labels:
    app: triangle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triangle
  template:
    metadata:
      labels:
        app: triangle
    spec:
      containers:
        - name: triangle
          image: triangle
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
